controller_list:
  - name: fake_cute_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_cute_gripper_controller
    joints:
      - claw